### PR TITLE
Use belovachap/chapman_cleanup_merge

### PR DESCRIPTION
**Pull request by belovachap**
Here's a branch that uses https://github.com/PeerAssets/btcpy/pull/16 as an example :)

### CODE REVIEW

**Comment by peerchemist** [comment]
Consider the following proposal:

Rather than doing pypeerassets/btcpy_peercoin.py to make a Transaction class which inherits the Transaction class from the btcpy and within it have a if/else on appropriate places which respond to tx_timestamp property of constants (https://github.com/PeerAssets/pypeerassets/blob/master/pypeerassets/networks.py#L20).

This was we get all the benefits and have a common interface for both Peercoin and Bitcoin. Also it covers all the scenarios with chains to be added in the future.

**Comment by belovachap** [comment]
Sure, I'll try making a `pypeerassets/transactions.py::Transaction` that is aware of `tx_timestamp` :robot: :rocket: :rooster: :rainbow:

**Comment by peerchemist** [comment]
You have that already here: https://github.com/PeerAssets/btcpy/blob/master/btcpy/structs/transaction.py#L705

**Comment by peerchemist** [comment]
Not sure what to do about this, bulk of tests fail.

**Comment by belovachap** [comment]
Hi again :wave: 

All the tests pass when I run the test suite locally :thinking: You have to run the tests locally since this branch relies on the feature branch https://github.com/PeerAssets/btcpy/pull/16 ( it's a little hidden but you can see this in the `requirements.txt` at the moment https://github.com/PeerAssets/pypeerassets/pull/125/files#diff-b4ef698db8ca845e5845c4618278f29aR2 ) :four_leaf_clover: 

This topic has gathered some dust but if we still want to pursue it my suggestion would be to:

1) Figure out if we're happy with https://github.com/PeerAssets/btcpy/pull/16 . If we are, merge it in and make a new version release for it.

2) Update this branch to use the new version of peerassets-btcpy

3) Profit! :champagne: 

https://vimeo.com/79954057

**Pull request merged**
